name: Build Image
on:
  push:
    branches:
      - main
      - feat/github-actions-build-image

jobs:
  duplicate_guard:
    runs-on: self-hosted
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/README.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  docker-build:
    needs: duplicate_guard
    if: ${{ needs.duplicate_guard.outputs.should_skip != 'true' }}
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up AWS Cli
        run: |
          sudo apt update -y
          sudo apt install awscli -y
          aws --version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        run: |
          docker login -u AWS -p $(aws ecr-public get-login-password --region us-east-1) public.ecr.aws/w1d0u6d8
      - name: Build and push images & upload to ECR
        id: build_images
        run: |
          docker build . -t jmt-monster-frontend:latest
          docker tag jmt-monster-frontend:latest public.ecr.aws/w1d0u6d8/jmt-monster-frontend:latest
          docker push public.ecr.aws/w1d0u6d8/jmt-monster-frontend:latest